Procrm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from crm.views import consultant

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', consultant.login),
    path('reg/', consultant.reg),
    path('crm/', include('crm.urls')),
    path('user_list/', consultant.user_list),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include, url

from crm.views import teacher,consultant

urlpatterns = [
    #公户
    #path('customer_list', views.customer_list,name='customer'),
    re_path(r'customer_list/', consultant.CustomerList.as_view(),name='customer'),
    # 私户
    #path('my_customer', views.customer_list, name='my_customer'),
    re_path(r'my_customer/', consultant.CustomerList.as_view(),name='my_customer'),
    #增加客户
    # path('customer/add/', views.add_customer, name='add_customer'),
    # path('customer/edit/<int:edit_id>', views.edit_customer, name='edit_customer'),
    #编辑客户
    # re_path(r'customer/edit/(\d+)', views.edit_customer, name='edit_customer')
    path('customer/add/', consultant.customer, name='add_customer'),
    re_path(r'customer/edit/(\d+)', consultant.customer, name='edit_customer'),
    #展示跟进记录
    re_path(r'consult_record_list/(\d+)', consultant.ConsultRecord.as_view(), name='consult_record'),
    #添加跟进记录
    re_path(r'consult_record/add/', consultant.consult_record, name='add_consult_record'),
    # 修改跟进记录
    re_path(r'consult_record/edit/(\d+)', consultant.consult_record, name='edit_consult_record'),
    # 展示报名记录
    re_path(r'enrollment_list/(?P<customer_id>\d+)', consultant.EnrollmentList.as_view(), name='enrollment'),
    # 添加报名记录
    re_path(r'enrollment/add/(?P<customer_id>\d+)', consultant.enrollment, name='add_enrollment'),
    # 编辑报名记录
    re_path(r'enrollment/edit/(?P<edit_id>\d+)', consultant.enrollment, name='edit_enrollment'),

    # 展示班级列表
    re_path(r'class_list/', teacher.ClassList.as_view(), name='class_list'),
    # 添加班级
    re_path(r'class/add/', teacher.classes, name='add_class'),
    # 编辑班级
    re_path(r'class/edit/(\d+)/', teacher.classes, name='edit_class'),
    # 展示某个班级的课程记录
    re_path(r'course_list/(?P<class_id>\d+)', teacher.CourseList.as_view(), name='course_list'),

    # 添加某个班级的课程记录
    re_path(r'course/add/(?P<class_id>\d+)/', teacher.courses, name='add_course'),
    # 编辑某个班级的课程记录
    re_path(r'course/edit/(?P<edit_id>\d+)/', teacher.courses, name='edit_course'),
    # 展示学习记录
    re_path(r'study_record_list/(?P<course_id>\d+)', teacher.study_record, name='study_record_list'),

]

crm/models.py
from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, User
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe
from django.urls import reverse

# Create your models here.
# Customer.sex
sex_type = (('male', '男'), ('female', '女'))
# Customer.source
source_type = (('qq', 'qq群'),
               ('referral', '内部转介绍'),
               ('website', '官方网站'),
               ('baidu_ads', '百度推广'),
               ('office_direct', '直接上门'),
               ('WoM', '口碑'),
               ('public_class', '公开课'),
               ('website_luffy', '路飞官网'),
               ('others', '其它'),)
# Customer.course
course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

# Customer.class_type
class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

# Customer.status
enroll_status_choices = (('signed', '已报名'),
                         ('unregistered', '未报名'),
                         ('studying', '学习中'),
                         ('paid_in_full', '学费已交齐'))

# ConsultRecord.status
seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)

pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Customer(models.Model):
    '''
    客户表
    '''
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex = models.CharField('性别', max_length=16, default='male', blank=True, null=True, choices=sex_type)
    birthday = models.DateField('出生日期', default=None, blank=True, null=True, help_text='格式yyyy-mm-dd')
    phone = models.BigIntegerField('手机号码', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name='转介绍自学员', blank=True, null=True, on_delete=models.CASCADE)
    course = MultiSelectField('咨询课程', choices=course_choices)
    class_type = models.CharField('班级类型', max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField('客户备注', blank=True, null=True)
    status = models.CharField('状态', choices=enroll_status_choices, max_length=64, default='unregistered',
                              help_text='选择客户此时的状态')
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')
    date = models.DateTimeField('咨询日期', auto_now_add=True)
    last_consult_date = models.DateField('最后跟进日期', auto_now_add=True)
    next_date = models.DateField('预计再次跟进时间', blank=True, null=True)
    network_consult = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                        related_name='network_consult', on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name='销售', related_name='customers', blank=True, null=True,
                                   on_delete=models.CASCADE)
    class_list = models.ManyToManyField('Classlist', verbose_name='已报班级')

    def show_status(self):
        """
        """

        color_dict = {
            "signed": "green",
            "unregistered": "red",
            "studying": "pink",
            "paid_in_full": "blue"
        }

        return mark_safe(
            '<span style= "background-color: {};color: white; padding: 4px">{}</span>'.format(color_dict[self.status],
                                                                                              self.get_status_display()))

    def show_classes(self):
        return ' | '.join([str(i) for i in self.class_list.all()])

    def enroll_link(self):

        if not self.enrollment_set.exists():
            return mark_safe('<a href={}">添加报名表</a>'.format(reverse('add_enrollment', args=(self.id,))))
        else:
            return mark_safe(
                '<a href={}">添加</a> | <a href={}">查看</a>'.format(reverse('add_enrollment', args=(self.id,)),
                                                                 reverse('enrollment', args=(self.id,))))

    def __str__(self):
        return self.name


class Campuses(models.Model):
    """
    校区表
    """

    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ContractTemplate(models.Model):
    """
    合同模板表
    """
    name = models.CharField('合同名称', max_length=128, unique=True)
    content = models.TextField('合同内容')
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区", on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,
                                 on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班级类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)

    def show_teachers(self):
        return "|".join([str(i) for i in self.teachers.all()])


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name='所咨询客户', on_delete=models.CASCADE)
    note = models.TextField(verbose_name='跟进内容')
    status = models.CharField('跟进状态', max_length=8, choices=seek_status_choices, help_text='选择客户此时的状态')
    consultant = models.ForeignKey('UserProfile', verbose_name='跟进人', related_name='records', on_delete=models.CASCADE)
    date = models.DateTimeField('跟进日期', auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    def __str__(self):
        return self.customer


class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField('为什么报名', max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称', on_delete=models.CASCADE)
    school = models.ForeignKey('Campuses', verbose_name='校区', on_delete=models.CASCADE)
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级", on_delete=models.CASCADE)

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """

    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True,
                                        on_delete=models.CASCADE)
    customer = models.ForeignKey('Customer', verbose_name="客户", on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", on_delete=models.CASCADE)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True, on_delete=models.CASCADE)

crm/forms.py
from django import forms
from django.core.exceptions import ValidationError

from crm import models

class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs.update({'class': 'form-control'})


class RegForm(BaseForm):

    password = forms.CharField(
        label="密码",
        widget=forms.widgets.PasswordInput(),
        min_length=6,
        error_messages={'min_length': '最小长度为6'},
    )

    re_password = forms.CharField(
        label="确认密码",
        widget=forms.widgets.PasswordInput(),
    )

    class Meta:
        model = models.UserProfile
        fields = ['username', 'password', 're_password', 'name', 'department']
        widgets = {
            'username': forms.widgets.EmailInput(attrs={"placeholder": "Email"}),
            'password': forms.widgets.PasswordInput(attrs={"placeholder": "Password"}),

        }

        labels = {
            'username': '用户名',
            'password': '密码',
            'name': '姓名',
            'department': '部门',
        }

        error_messages = {
            'password': {
                'required': '密码不能空',
            }
        }

    def clean(self):
        pwd = self.cleaned_data.get('password')
        re_pwd = self.cleaned_data.get('re_password')

        if pwd == re_pwd:
            return self.cleaned_data
        self.add_error('re_password', '两次密码不一致')
        raise ValidationError('两次秘密不一致')

# 客户form
class CustomerForm(BaseForm):

    class Meta:
        model =  models.Customer
        fields='__all__'
        widgets ={
            'course':forms.widgets.SelectMultiple,
            'birthday':forms.widgets.DateInput
        }


# 跟进记录form
class ClassRecordForm(BaseForm):

    class Meta:
        model =  models.ConsultRecord
        exclude=['delete_status']

        # widgets={
        #     'customer':forms.widgets.Select(choices=((1,'xxx')))
        # }

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        customer_choices=[ (i.id,i) for i in self.instance.consultant.customers.all()]
        customer_choices.insert(0,('','----------'))
        consultant_choices=[ (self.instance.consultant.id, self.instance.consultant)]
        self.fields['customer'].widget.choices=customer_choices
        self.fields['consultant'].widget.choices = consultant_choices

# 跟进记录form
# class EnrollmentForm(BaseForm):
#
#     class Meta:
#         model =  models.Enrollment
#         exclude=['delete_status','contract_approved']
#
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         # 限制当前的客户只能是传的id对应的客户
#         self.fields['customer'].widget.choices = [(self.instance.customer.id, self.instance.customer), ]
#         # 限制当前可报名班级是当前客户的意向班级
#         self.fields['enrolment_class'].widget.choices= [(i.id,i) for i in self.instance.customer.class_list.all()]


# 报名表Form
class EnrollmentForm(BaseForm):
    class Meta:
        model = models.Enrollment
        exclude = ['delete_status', 'contract_approved']
        labels = {}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs.update({'class': 'form-control'})

        # 限制当前的客户只能是传的id对应的客户
        self.fields['customer'].widget.choices = [(self.instance.customer_id, self.instance.customer), ]
        # 限制当前可报名的班级是当前客户的意向班级
        self.fields['enrolment_class'].widget.choices = [(i.id, i) for i in self.instance.customer.class_list.all()]


#班级Form
class ClassForm(BaseForm):
    forms.DateField(label='日期', )
    class Meta:
        model=models.ClassList
        fields='__all__'

    start_date = forms.DateField(
        label="开班日期",
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs.update({'class': 'form-control'})

class CourseForm(BaseForm):

    class Meta:
        model=models.CourseRecord
        fields='__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 限制当前的客户只能是传的id对应的客户
        self.fields['re_class'].widget.choices = [(self.instance.re_class_id, self.instance.re_class)]
        # 限制当前可报名的班级是当前客户的意向班级
        self.fields['teacher'].widget.choices = [(self.instance.teacher_id, self.instance.teacher)]

class StudyRecordForm(BaseForm):

    class Meta:
        model=models.StudyRecord
        fields=['attendance','score','homework_note','student']

templates/crm/consult_record_list.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        th, td {
            text-align: center;
        }


    </style>
{% endblock %}

{% block content %}
    <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Panel heading</div>
    <div class="panel-body">
        <a href="{% url 'add_consult_record' %}" class="btn btn-primary btn-sm ">添加跟进记录</a>
        <div class="form-group">
            <form action="" class="form-inline pull-right">
                <input type="text" name="query" class="form-control" placeholder="搜索">
                <button type="submit" class="btn btn-primary btn-sm">搜索<i class="fa fa-search-plus"></i></button>
            </form>
        </div>
        <form action="" method="post" class="form-inline">
            {% csrf_token %}
            <select name="action" class="form-control" style="margin: 5px 0">
                <option value="">请选择</option>
                <option value="multi_delete">删除</option>
            </select>
            <button type="submit" class="btn btn-success btn-sm">提交</button>

            <!-- Table -->
            <table class="table table-bordered table-hover th">
                <thead>
                <tr>
                    <th><input type="checkbox" id="selectAll"/></th>
                    <th>序号</th>
                    <th>客户</th>
                    <th>跟进内容</th>
                    <th>跟进状态</th>
                    <th>跟进日期</th>
                    <th>跟进人</th>
                    <th>修改</th>
                </tr>
                </thead>
                <tbody>
                {% for record in all_consult_record %}
                    <tr>
                        <td><input type="checkbox" name='id' value="{{ record.id }}"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ record.customer }}</td>
                        <td>{{ record.note }}</td>
                        <td>{{ record.get_status_display }}</td>
                        <td>{{ record.date }}</td>
                        <td>{{ record.consultant }}</td>
                        <td><a href="{% url 'edit_consult_record' record.id %}}"><i class="fa fa-edit fa-fw"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </form>

    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ pagination }}
        </ul>
    </nav>


{% endblock %}

{% block js %}
    <script>
        $(function () {
            $("#selectAll").click(function () {
                $(":checkbox[name='id']").prop("checked", this.checked);
            })

        })

    </script>
{% endblock %}

templates/crm/customer_list.html
{% extends 'layout.html' %}

{% block css %}
    <style>
        th, td {
            text-align: center;
        }


    </style>
{% endblock %}

{% block content %}
    <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Panel heading</div>
    <div class="panel-body">
        {{ add_btn }}
        <div class="form-group">
            <form action="" class="form-inline pull-right">
                <input type="text" name="query" class="form-control" placeholder="搜索">
                <button type="submit" class="btn btn-primary btn-sm">搜索<i class="fa fa-search-plus"></i></button>
            </form>
        </div>
        <form action="" method="post" class="form-inline">
            {% csrf_token %}
            <select name="action" class="form-control" style="margin: 5px 0">
                <option value="">请选择</option>
                <option value="multi_delete">删除</option>
                <option value="multi_pub">放入公户</option>
                <option value="multi_apply">放入私户</option>
            </select>
            <button type="submit" class="btn btn-success btn-sm">提交</button>

            <!-- Table -->
            <table class="table table-bordered table-hover th">
                <thead>
                <tr>
                    <th><input type="checkbox" id="selectAll"/></th>
                    <th>序号</th>
                    <th>QQ</th>
                    <th>姓名</th>
                    <th>手机号码</th>
                    <th>客户来源</th>
                    <th>咨询课程</th>
                    <th>班级类型</th>
                    <th>状态</th>
                    <th>咨询日期</th>
                    <th>销售</th>
                    <th>已报班级</th>
                    <th>跟进记录</th>
                    {% if request.path_info == '/crm/my_customer/' %}
                        <th>添加记录</th>
                        <th>操作</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for customer in all_customer %}
                    <tr>
                        <td><input type="checkbox" name='id' value="{{ customer.id }}"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ customer.qq }}</td>
                        <td>{{ customer.name }}</td>
                        <td>{{ customer.phone }}</td>
                        <td>{{ customer.get_source_display }}</td>
                        <td>{{ customer.course }}</td>
                        <td>{{ customer.get_class_type_display }}</td>
                        <td>{{ customer.show_status }}</td>
                        <td>{{ customer.date }}</td>
                        <td>{{ customer.consultant }}</td>
                        <td>{{ customer.show_classes }}</td>
                        {% if request.path_info == '/crm/my_customer/' %}
                            <td><a href="{% url 'consult_record' customer.id %}">跟进记录</a></td>
{#                            <td><a href="{% url 'add_enrollment' customer.id %}}?{{ query_params }}">添加报名表</a></td>#}
                            <td>{{ customer.enroll_link }}</td>

                        {% endif %}
                        <td><a href="{% url 'edit_customer' customer.id %}}?{{ query_params }}"><i class="fa fa-edit fa-fw"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </form>

    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ pagination }}
        </ul>
    </nav>


{% endblock %}

{% block js %}
    <script>
        $(function () {
            $("#selectAll").click(function () {
                $(":checkbox[name='id']").prop("checked", this.checked);
            })

        })

    </script>
{% endblock %}

templates/crm/form.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            {{ title }}
        </div>
        <div class="panel-body">
            <div class="col-sm-8 col-sm-offset-2">
                <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form_obj %}

                        <div class="form-group row {% if field.errors %}has-error{% endif %} ">

                            <label for="{{ field.id_for_label }}"
                                   class="col-sm-2 control-label"> {{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field }}
                                <span class="help-block">
                        {{ field.errors.0 }}
                    </span>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}